[workspace]
members = ["crates/*", "bindings/node/*" ]
members = ["crates/*"]
ignoredFolders = [
  "$HOME",
  "$HOME/.cargo/**",
  "$HOME/.rustup/**"
]
[build]
rustdocflags = ["--document-private-items"]
