[workspace]
members = ["crates/common", "crates/core", "crates/cube_model", "crates/database", "crates/glyph_engine", "crates/macro_tests", "crates/macros/*", "crates/model_common", "bindings/node/*" ]

ignoredFolders = [
  "$HOME",
  "$HOME/.cargo/**",
  "$HOME/.rustup/**"
]
[build]
rustdocflags = ["--document-private-items"]
