[package]
name = "glyph_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
glyphx_core = { path = "../core" }
glyphx_common = { path = "../common" }
glyphx_database = { path = "../database" }
im = "15.1.0"
lazy_static = "1.4.0"
mockall = "0.11.4"
serde = "1.0.163"
serde_json = "1.0.107"
tokio = { version = "1", features = ["full"] }
