[package]
name = "glyph_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glyphx_core = { path = "../core" }
glyphx_common = { path = "../common" }
glyphx_database = { path = "../database" }
serde = "1.0.163"
serde_json = "1.0.107"
lazy_static = "1.4.0"
