export enum DateGrouping {
  QualifiedDayOfYear = 'qualified_day_of_year',
  DayOfYear = 'day_of_year',
  QualifiedDayOfMonth = 'qualified_day_of_month',
  YearDayOfMonth = 'year_day_of_month',
  MonthDayOfMonth = 'month_day_of_month',
  DayOfMonth = 'day_of_month',
  QualifiedDayOfWeek = 'qualified_day_of_week',
  DayOfWeek = 'day_of_week',
  QualifiedWeekOfYear = 'qualified_week_of_year',
  WeekOfYear = 'week_of_year',
  QualifiedMonth = 'qualified_month',
  MonthOfYear = 'month_of_year',
  Year = 'year',
  QualifiedQuarter = 'qualified_quarter',
  Quarter = 'quarter',
  YearOfWeek = 'year_of_week',
}
