// determines what to show in the modal utility
export enum MODAL_CONTENT_TYPE {
  CREATE_PROJECT = 'CREATE_PROJECT',
  CREATE_WORKSPACE = 'CREATE_WORKSPACE',
  DELETE_ACCOUNT = 'DELETE_ACCOUNT',
  DELETE_WORKSPACE = 'DELETE_WORKSPACE',
  DELETE_PROJECT = 'DELETE_PROJECT',
  FILE_DECISIONS = 'FILE_DECISIONS',
  FILE_ERRORS = 'FILE_ERRORS',
}
