export enum ACTION_TYPE {
  CREATED = 'CREATED',
  FILES_INGESTED = 'FILES_INGESTED',
  MODEL_GENERATED = 'MODEL_GENERATED',
  UPDATED = 'UPDATED',
  ROLE_UPDATED = 'ROLE_UPDATED',
  DELETED = 'DELETED',
  MOVED = 'MOVED',
  WORKSPACE_JOINED = 'WORKSPACE_JOINED',
  INVITED = 'INVITED',
  INVITATION_DECLINED = 'INVITATION_DECLINED',
  INVITATION_ACCEPTED = 'INVITATION_ACCEPTED',
  PROCESS_TRACKING = 'PROCESS_TRACKING',
}
