export enum ACTION_TYPE {
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  ROLE_UPDATED = 'ROLE_UPDATED',
  DELETED = 'DELETED',
  MOVED = 'MOVED',
  WORKSPACE_JOINED = 'WORKSPACE_JOINED',
  INVITED = 'INVITED',
  INVITATION_DECLINED = 'INVITATION_DECLINED',
  INVITATION_ACCEPTED = 'INVITATION_ACCEPTED',
}
