export enum EmailTypes {
  EMAIL_UPDATED = 'EMAIL_UPDATED',
  EMAIL_VERFICATION = 'EMAIL_VERFICATION',
  STATE_CREATED = 'STATE_CREATED',
  WORKSPACE_CREATED = 'WORKSPACE_CREATED',
  WORKSPACE_INVITATION = 'WORKSPACE_INVITATION',
  WORKSPACE_JOINED = 'WORKSPACE_JOINED',
  ANNOTATION_CREATED = 'ANNOTATION_CREATED',
}
