[package]
name = "glyphx_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.55.3"
aws-sdk-s3 = "0.28.0"
backtrace = "0.3.67"
chrono = "0.4.24"
json5 = "0.4.1"
log = "0.4.17"
log4rs = "1.2.0"
serde = "1.0.163"
serde_derive = "1.0.163"
serde_json = "1.0.96"
serial_test = "2.0.0"
tokio = { version = "1", features = ["full"] }
